import { Product, Order, Customer } from './types';

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Headphones Ultra Pro',
    category: 'Electronics',
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    reviewCount: 1247,
    stock: 45,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=600',
    brand: 'SoundMax',
    description: 'Premium noise-cancelling wireless headphones with 40-hour battery life.',
    tags: ['wireless', 'noise-cancelling', 'premium'],
  },
  {
    id: 'p2',
    name: 'Running Shoes Elite',
    category: 'Footwear',
    price: 189,
    originalPrice: 240,
    rating: 4.6,
    reviewCount: 832,
    stock: 28,
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=600',
    brand: 'SpeedRun',
    description: 'Professional running shoes with carbon fiber plate and responsive foam.',
    tags: ['running', 'performance', 'sport'],
  },
  {
    id: 'p3',
    name: 'Backpack Premium X',
    category: 'Bags',
    price: 129,
    originalPrice: 159,
    rating: 4.7,
    reviewCount: 564,
    stock: 62,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=600',
    brand: 'CarryPro',
    description: '35L waterproof backpack with laptop compartment and USB charging port.',
    tags: ['travel', 'waterproof', 'laptop'],
  },
  {
    id: 'p4',
    name: 'Smart Watch Series 7',
    category: 'Electronics',
    price: 449,
    originalPrice: 549,
    rating: 4.9,
    reviewCount: 2103,
    stock: 15,
    image: 'https://images.pexels.com/photos/393047/pexels-photo-393047.jpeg?auto=compress&cs=tinysrgb&w=600',
    brand: 'TechWear',
    description: 'Advanced smartwatch with health monitoring, GPS, and 72-hour battery.',
    tags: ['smartwatch', 'health', 'GPS'],
  },
  {
    id: 'p5',
    name: 'Wireless Keyboard K90',
    category: 'Electronics',
    price: 149,
    originalPrice: 199,
    rating: 4.5,
    reviewCount: 417,
    stock: 89,
    image: 'https://images.pexels.com/photos/1194713/pexels-photo-1194713.jpeg?auto=compress&cs=tinysrgb&w=600',
    brand: 'TypeMaster',
    description: 'Mechanical wireless keyboard with RGB backlighting and 6-month battery.',
    tags: ['mechanical', 'wireless', 'RGB'],
  },
  {
    id: 'p6',
    name: 'Gaming Mouse Pro',
    category: 'Electronics',
    price: 89,
    originalPrice: 119,
    rating: 4.7,
    reviewCount: 1893,
    stock: 134,
    image: 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=600',
    brand: 'GameEdge',
    description: '25600 DPI gaming mouse with 11 programmable buttons and optical sensor.',
    tags: ['gaming', 'high-dpi', 'programmable'],
  },
  {
    id: 'p7',
    name: 'Executive Office Chair',
    category: 'Furniture',
    price: 599,
    originalPrice: 799,
    rating: 4.4,
    reviewCount: 328,
    stock: 8,
    image: 'https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg?auto=compress&cs=tinysrgb&w=600',
    brand: 'ErgoLux',
    description: 'Ergonomic executive chair with lumbar support and 4D armrests.',
    tags: ['ergonomic', 'office', 'lumbar'],
  },
  {
    id: 'p8',
    name: 'Laptop Stand Aluminium',
    category: 'Accessories',
    price: 79,
    originalPrice: 99,
    rating: 4.6,
    reviewCount: 712,
    stock: 200,
    image: 'https://images.pexels.com/photos/4158/apple-iphone-smartphone-desk.jpg?auto=compress&cs=tinysrgb&w=600',
    brand: 'DeskPro',
    description: 'Adjustable aluminium laptop stand with 6 height levels and ventilation.',
    tags: ['aluminium', 'adjustable', 'portable'],
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-2024-001',
    customer: 'Alexandra Chen',
    customerEmail: 'alexandra@email.com',
    date: '2024-01-15',
    products: [{ name: 'Smart Watch Series 7', qty: 1, price: 449 }, { name: 'Laptop Stand', qty: 1, price: 79 }],
    status: 'completed',
    total: 528,
    shippingAddress: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-002',
    customer: 'Marcus Johnson',
    customerEmail: 'marcus@email.com',
    date: '2024-01-16',
    products: [{ name: 'Headphones Ultra Pro', qty: 1, price: 299 }],
    status: 'processing',
    total: 299,
    shippingAddress: '456 Oak Ave, Los Angeles, CA 90001',
  },
  {
    id: 'ORD-2024-003',
    customer: 'Sofia Rodriguez',
    customerEmail: 'sofia@email.com',
    date: '2024-01-17',
    products: [{ name: 'Running Shoes Elite', qty: 2, price: 378 }],
    status: 'pending',
    total: 378,
    shippingAddress: '789 Pine Rd, Miami, FL 33101',
  },
  {
    id: 'ORD-2024-004',
    customer: 'James Wilson',
    customerEmail: 'james@email.com',
    date: '2024-01-18',
    products: [{ name: 'Gaming Mouse Pro', qty: 1, price: 89 }, { name: 'Wireless Keyboard', qty: 1, price: 149 }],
    status: 'completed',
    total: 238,
    shippingAddress: '321 Elm St, Chicago, IL 60601',
  },
  {
    id: 'ORD-2024-005',
    customer: 'Priya Patel',
    customerEmail: 'priya@email.com',
    date: '2024-01-19',
    products: [{ name: 'Office Chair Executive', qty: 1, price: 599 }],
    status: 'cancelled',
    total: 599,
    shippingAddress: '654 Maple Ln, Seattle, WA 98101',
  },
  {
    id: 'ORD-2024-006',
    customer: 'David Kim',
    customerEmail: 'david@email.com',
    date: '2024-01-20',
    products: [{ name: 'Backpack Premium X', qty: 1, price: 129 }],
    status: 'processing',
    total: 129,
    shippingAddress: '987 Cedar Blvd, Austin, TX 78701',
  },
];

export const customers: Customer[] = [
  {
    id: 'C001',
    name: 'Alexandra Chen',
    email: 'alexandra@email.com',
    phone: '+1 (555) 234-5678',
    orders: 12,
    totalSpent: 3847,
    status: 'active',
    joinDate: '2023-03-15',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
  {
    id: 'C002',
    name: 'Marcus Johnson',
    email: 'marcus@email.com',
    phone: '+1 (555) 345-6789',
    orders: 7,
    totalSpent: 1923,
    status: 'active',
    joinDate: '2023-05-22',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
  {
    id: 'C003',
    name: 'Sofia Rodriguez',
    email: 'sofia@email.com',
    phone: '+1 (555) 456-7890',
    orders: 4,
    totalSpent: 987,
    status: 'active',
    joinDate: '2023-08-10',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
  {
    id: 'C004',
    name: 'James Wilson',
    email: 'james@email.com',
    phone: '+1 (555) 567-8901',
    orders: 18,
    totalSpent: 5234,
    status: 'active',
    joinDate: '2022-11-30',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
  {
    id: 'C005',
    name: 'Priya Patel',
    email: 'priya@email.com',
    phone: '+1 (555) 678-9012',
    orders: 2,
    totalSpent: 647,
    status: 'inactive',
    joinDate: '2023-12-05',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
  {
    id: 'C006',
    name: 'David Kim',
    email: 'david@email.com',
    phone: '+1 (555) 789-0123',
    orders: 9,
    totalSpent: 2156,
    status: 'active',
    joinDate: '2023-02-14',
    avatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
];

export const revenueData = [
  { month: 'Jul', revenue: 42000, orders: 320 },
  { month: 'Aug', revenue: 51000, orders: 389 },
  { month: 'Sep', revenue: 47000, orders: 356 },
  { month: 'Oct', revenue: 63000, orders: 478 },
  { month: 'Nov', revenue: 78000, orders: 592 },
  { month: 'Dec', revenue: 94000, orders: 712 },
  { month: 'Jan', revenue: 71000, orders: 541 },
];

export const categoryData = [
  { name: 'Electronics', value: 45, color: '#FF6B00' },
  { name: 'Footwear', value: 20, color: '#0B1F3A' },
  { name: 'Accessories', value: 15, color: '#22C55E' },
  { name: 'Bags', value: 12, color: '#3B82F6' },
  { name: 'Furniture', value: 8, color: '#F59E0B' },
];
